# add apache2
- name: Install apache2
  apt:
    name: "apache2"
    state: present  # not using latest package to avoid time consuming checks for prepared images

- name: Install Ganglia
  apt:
    name: ["ganglia-webfrontend","gmetad"]
    state: present

- copy:
    src: ganglia/gmetad.conf
    dest: /etc/ganglia/gmetad.conf
    owner: root
    group: root
    mode: 0644

- name: (Re-)start gmetad
  systemd:
    name: gmetad
    state: restarted
    enabled: yes

- name: Configure Ganglia
  copy:
    src: ganglia/ganglia.conf
    dest: /etc/apache2/sites-available/ganglia.conf
    owner: root
    group: root
    mode: 0644
    
- name: Enable Ganglia sites
  shell: "/usr/sbin/a2ensite ganglia"
  args:
    creates: /etc/apache2/sites-enabled/ganglia.conf
  register: ganglia_site_enabled
    
- name: (Re-)start Apache
  systemd:
    name: apache2
    state: restarted
    enabled: yes
  when: ganglia_site_enabled



