- name: Install Slurm packages
  apt:
    name: ["slurm-wlm", "libslurm-dev", "slurmdbd"]
    state: latest


# (Re-)start slurmdbd master daemon
- name: (Re-)start slurmdbd master
  systemd:
    name: slurmdbd
    enabled: True
    state: restarted
  when: slurmdb_conf is changed or slurm_conf is changed or slurm_cggroup_conf is changed

# (Re-)start slurmctl master daemon
- name: (Re-)start slurmctld master
  systemd:
    name: slurmctld
    enabled: True
    state: restarted
  when: slurm_conf is changed or slurmdb_conf is changed or slurm_cggroup_conf is changed or SLURM_cgroup_allowed_devices_conf is changed

# (Re-)start slurmd worker daemon
- name: (Re-)start slurmd worker daemon
  systemd:
    name: slurmctld
    enabled: True
    state: restarted
  when:
    - use_master_as_compute == 'yes'
    - slurm_conf is changed or slurmdb_conf is changed or slurm_cggroup_conf is changed or SLURM_cgroup_allowed_devices_conf is changed

#- name: add cluster to accounting
#  ansible.builtin.shell: sacctmgr -i add cluster "{{ scheduler_config.cluster_name }}"
#  args:
#    executable: /bin/bash

# copy
- name: Copy GridEngine compatible layer
  copy:
    src: slurm/qsub
    dest: /usr/local/bin/qsub
    mode: 0755
    owner: root
    group: root

- copy:
    src: slurm/gridengine-rc
    dest: /home/ubuntu/.gridengine-rc
    mode: 0600
    owner: ubuntu
    group: ubuntu


- name: sacctmgr show cluster and store in slurm_clusterlist variable
  command: "sacctmgr -n show cluster {{ scheduler_config.cluster_name }}"
  register: slurm_clusterlist
  changed_when: False

- name: add cluster to accounting
  command: "sacctmgr -i add cluster {{ scheduler_config.cluster_name }}"
  when: ' scheduler_config.cluster_name|string not in slurm_clusterlist.stdout'


- name: restart slurmctld - missing cluster
  systemd:
    name: slurmctld
    enabled: True
    state: restarted
  when: ' "127.0.0.1" not in slurm_clusterlist.stdout'