- block:
  - debug:
      msg: "[BIBIGRID] Setup Ganglia monitor"
  - include: 001-ganglia.yml
  tags: ["master-ganglia","ganglia"]
  when:
    - enable_ganglia == 'yes'
    - ansible_distribution_release == 'xenial'

- block:
    - debug:
        msg: "[BIBIGRID] Setup Zabbix Server"
    - include: 002-zabbix.yml
  tags: ["master-zabbix","zabbix"]
  when:
    - enable_zabbix == 'yes'

- debug:
    msg: "[BIBIGRID] Mount disk"
- include: 005-disk.yml
  tags: ["master-disk","disk"]

- debug:
    msg: "[BIBIGRID] Setup NFS"
  when:
    - enable_nfs == 'yes'
- include: 010-nfs.yml
  when:
    - enable_nfs == 'yes'
  tags: ["master-nfs","nfs"]

- debug:
    msg: "[BIBIGRID] Setup GridEngine"
  when:
    - enable_gridengine == 'yes'
- include: 020-gridengine.yml
  when:
    - enable_gridengine == 'yes'
  tags: ["master-gridengine","gridengine"]

- debug:
    msg: "[SCALING] virtualenv"
- import_tasks: 015-virtualenv.yml
  tags: ["virtualenv"]

- debug:
    msg: "[SCALING] Setup mysql db"
- include: 018-mysql.yml
  when:
    - enable_slurm == 'yes'
  tags: ["master-mysql","mysql","slurm"]

- block:
  - debug:
      msg: "[BIBIGRID] Setup Slurm master"

  - include: 021-slurm.yml
  when:
    - enable_slurm == 'yes'
  tags: ["master-slurm","slurm","scale-up","scale-down"]

- debug:
    msg: "[BIBIGRID] Setup Theia"
  when:
    - enable_ide == 'yes'
- include: 999-theia.yml
  when:
    - enable_ide == 'yes'
  tags: ["master-theia","theia"]


- debug:
    msg: "[SCALING] worker dummy setup"
- import_tasks: 111-hosts_dummy.yml
  tags: ["dummy_worker"]

- debug:
    msg: "[SCALING] pyslurm in virtualenv"
- import_tasks: 121-pyslurm.yml
  tags: ["pyslurm"]

- debug:
    msg: "[SCALING] autoscaling conf"
- import_tasks: 122-autoscaling.yml
  tags: ["autoscaling"]

